language: node_js
node_js:
  - "9"
env:
  global:
    - GITHUB_ORG="https://GH_TOKEN@github.com/book-monkey2-build"
    - GITHUB_NAME="The Buildbot"
    - GITHUB_EMAIL="buildbot@angular2buch.de"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- echo "ramu"
- ng lint
- npm run bp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: dist/ChatApp
  on:
    branch: master
